### ISSUE TITLE
Revalidate features after Java change

### ISSUE THREAD

**Issue by rlogiacco** [rlogiacco/Natural#11]
When a Java build occurs the plugin must re execute the EValidator to check if change has fixed or broken any matching between steps and stepdefs.

Right now to verify this you have to open the feature file and force a re validation by modifying and saving it, which is impractical.

The current easiest way to check the entire feature sets is to issue a clean build, which should be documented.
##

**Comment by drkstr101** [comment]
@rlogiacco Could you please provide a little more details on what you would like to happen with this?

Cheers!

**Comment by rlogiacco** [comment]
Right now the feature file gets parsed upon change, but if I change a stepdef the matching changes are not reflected on the feature file.

Example: feature file has 3 stepdefs, 1 is not matched and highlighted with a warning; I implement the missing stepdef, the warning stays there in the feature file until I change the feature file.

What I wish to have is the feature file to listen for Java compilation events and run the step matching routine in background when that happens.

**Comment by drkstr101** [comment]
Got it, thanks!

Flagging for review in [next](https://github.com/rlogiacco/Natural/pull/73).
