### ISSUE TITLE
Customize folding regions

### ISSUE THREAD

**Issue by rlogiacco** [rlogiacco/Natural#13]
By using [this suggestion](http://www.eclipse.org/forums/index.php/mv/tree/170825/#page_top) the folding regions should be customized to match the gherkin syntax.

The idea is to allow folding of scenarios, scenario outlines, background and steps containing tables/docstrings only. 

All other elements (tags, simple steps) should not be foldable but they currently are and folding regions are not properly computed due to EOL usage in the grammar.
##

**Comment by drkstr101** [comment]
Flagging for review in [next](https://github.com/rlogiacco/Natural/pull/73).
