### ISSUE TITLE
Support Task Tags (i.e.: TODO or FIXME)

### ISSUE THREAD

**Issue by robertoandrade** [rlogiacco/Natural#26]
Many plugin's editors allow configuration (as well as with generic Eclipse editor preferences) to configure which Content Types and files should be included in Tasks discovery for listing in the Tasks view. It would be nice this this plugin supported it as well so comments like:
# TODO: Need to add a scenario here for XYZ.

Would show up alongside other tasks in the IDE.
##

**Comment by miklossy** [comment]
This feature is available since Xtext 2.6.0 (see [commit](https://github.com/eclipse/xtext-eclipse/commit/b34080919246849a0dc0977f23a4edc2748dcbff)) and should work out-of-the box without additional configuration.

**Comment by drkstr101** [comment]
Thanks for the update!

@rlogiacco Please close issue.

**Comment by rlogiacco** [comment]
Fixed in `0.7.7` and `0.3.1`
