### ISSUE TITLE
Cucumber editor can't handle large projects

### ISSUE THREAD

**Issue by jakub-bochenski** [rlogiacco/Natural#33]
I've installed the plugin on a brand new eclipse install with xtext 2.3.1
When I load my project, which has ~4,700 classes (not even any cucumber binidngs, just regular java project) eclipse will eat 100% of cpu. Even building the projects takes several minutes.
After uninstalling xtext and cucumber editor things got  back to normal.
##

**Comment by rlogiacco** [comment]
Just an update on this: I believe I've found a few performance improvements and I might add the possibility to specify a package filtering option in the plugin preferences for the project to reduce the amount of classes getting scanned for annotations. 

This might lead to a much better performance when the plugin is used on a huge workspace.

I'll come back as soon as I manage to prepare a new release.

**Comment by rlogiacco** [comment]
I've built a newer version which should improve performance on large projects: please share your feedback on this.

**Comment by rlogiacco** [comment]
Closing as never got any feedback
