### ISSUE TITLE
Enable reverse-lookup

### ISSUE THREAD

**Issue by TrueDub** [rlogiacco/Natural#4]
It would be handy to be able to do the following:

When you have a step definition java class, click on the Cucumber condition (@Then, @When etc) and get a list of feature files where that condition is used. The output could be similar to the search dialog in Eclipse.
##

**Comment by alqh** [comment]
Also, possibly warn for those step definitions that are not in used (similar to unused variables error) to allow developer to clean up unused step defs especially when step defs spans across multiple classes?

**Comment by rlogiacco** [comment]
That would be a nice feature: are you willing to implement it?
