### ISSUE TITLE
Content assitance is getting auto sorted

### ISSUE THREAD

**Issue by devisuresh** [rlogiacco/Natural#41]
Hi All,

We have customized the content assist of natural plugin to display our own content as content assist for our project. This works good currently. But this contents were getting auto sorted to ascending order while displaying it in the feature file. We want to display the content assist in the order which we have in the proposal list object in JavaAnnotationMatcher.findProposals() method. 

Any way can we stop this auto sorting and display the content assist in the order as we have in the proposal object.

Thanks in Advance.
##

**Comment by rlogiacco** [comment]
I believe there is a way to establish a precedence or grouping, but I'm not sure how to get that as my knowledge of the Eclipse API is limited. 

As I'm using Xtext which, in turn, uses plain Eclipse RCP and because I see in my IDE some sort of precedence on the Java content assist, I don't see why the same couldn't be achieved on the Natural plugin: please let me know if you succeed in the task.

BTW, I'm curious to know what type of sorting are you trying to push into the proposals.

**Comment by devisuresh** [comment]
Thanks Robert.

Am trying to show up the first level content assist list items first and then the second level content assist list items. So i have added the first level content assist to proposal object and then added the second level content assist list items.  Then i want to display the proposal list contents in the same order which the proposal object holds. But the list items were getting auto sorted and displayed in ascending order.

**Comment by sivaprasad09** [comment]
Hi rlogiacco,

can we have a content assist as subword search for proposal. When I am using Intellij as a IDE I am getting subword(regular expression) content assist. When I am trying add plugin for eclipse i had chosen natural which has all features but only missing part is subword content assist. if you add a code for this that will great.

**Comment by rlogiacco** [comment]
Hi, can you get into the details of what you would expect with subword
content assist? It's not clear to me what this means

**Comment by rlogiacco** [comment]
No comments received

**Comment by sivaprasad09** [comment]
I am looking for the regular expression auto fill in natural editor. 
we are using natural plugin for BDD automation. when i enter given and ctrl+space it displays when it matches with starting letter but we are looking for regular expression search in a sentence(if any word matches in sentence then it should display)

**Comment by rlogiacco** [comment]
Does it have to do with content assist sorting?

Do you have a fix?

**Comment by sivaprasad09** [comment]
No I don't have any fix right now. I am trying to do it. Do you have
anything existing

**Comment by rlogiacco** [comment]
No. When you have something working feel free to submit a pull request mentioning this issue.

**Comment by rlogiacco** [comment]
Four years is long enough....
