### ISSUE TITLE
Groovy step definitions

### ISSUE THREAD

**Issue by halatas** [rlogiacco/Natural#46]
I am using cucumber in eclipse mars/gradle/groovy setup. The groovy step definitions run perfectly fine on command line, however I could not get the plugin to work. Defined steps do not appear on auto complete list and I still see feature steps as "not defined" on editor. 

Could you please let me know if this is requires additional development or is an issue on my setup?
##

**Comment by rlogiacco** [comment]
There is additional development required in order to search the matching stepdefs in Groovy files, at this stage the plugin only looks for Java files and, even on that front, it requires some improvements.

You are welcome to contribute.

**Comment by halatas** [comment]
I would like to when I find time, however I am a complete noob on eclipse plugin development, could you please give a few clues on where to start?

**Comment by rlogiacco** [comment]
Start from Xtext and the project wiki. When I wrote this plugin I was a complete noob on eclipse pligin development myself and still now i consider myself a noob :)

**Comment by halatas** [comment]
I am getting many missing Class and Package issues when I import the project. For example in org.agileware.natural.cucumber, i can not find org.agileware.natural.cucumber package which is supposed to have CucumberGrammarAccess in it. Am i missing something obvious?

**Comment by rlogiacco** [comment]
​There are multiple classes that need to be generated in order to resolve a
few compilation errors. Generation occurs via Xtext  Have you read the wiki
page https://github.com/rlogiacco/Natural/wiki/Contribute?​

**Comment by JacksonBailey** [comment]
As a "workaround" is there anyway to turn off the warnings while still using the editor for its syntax support?

**Comment by drkstr101** [comment]
I have a bit of experience working with eclipse plugins, and deadlocked Eclipse every time I edit a feature file with Groovy backed stepdefs. I also happen to be fairly knowledgeable of Groovy, including many of its compat issues. I will see if I can hop in here and at least prevent it from bringing down Eclipse. I will post back once I've been able to groc the codebase and get your feedback on some proposed changes.

Cheers, and thanks for your time!

**Comment by drkstr101** [comment]
PS: The other `cucumber-eclipse` plugin in marketplace has the same issue. I'm not sure if it's a common dependency or a common design flaw. I'm poking around in there too to see if that helps narrow down the defect.

**Comment by rlogiacco** [comment]
Hey @drkstr101 you are very welcome to join in. To be honest I lost interest because everyone who comes here and promised to provide help has never fulfilled and I've always been left alone. I truly hope you will make me change my mind and regain interest into this plugin.

So, to chime someone famous: yes we can, if you want.

**Comment by drkstr101** [comment]
Awesome, thanks for the reply! I've been able to get the workspace up and running, now I'm just attempting to digest the code. I haven't done anything major with XText before, but I'm starting to get the hang of it. I'm sure I'll have questions. Glad to know you are still active here in that case.

Cheers!

**Comment by drkstr101** [comment]
This is now working much better in https://github.com/rlogiacco/Natural/pull/73 but it could still use a little work for an ideal user experience.

**Comment by rlogiacco** [comment]
As #73 was closed without merging, is this also part of #82 ? Otherwise please re-open this issue: thanks.

**Comment by drkstr101** [comment]
This one can also be closed. Groovy step defs are working in my large(ish) project. The only change was really the upgrade to Java 1.8 target + deps upgrade + flag in the validator to mark it as expensive. This flag changes the defaults on how and when it is executed. All of the above seemed to fix the issue, in my use case at least. Further smoke testing would be appreciated.
