### ISSUE TITLE
Incompatibility with latest versions of Xtext

### ISSUE THREAD

**Issue by PyvesB** [rlogiacco/Natural#48]
Hello rlogiacco,

I was having issues when installing the Cucumber Natural component, and after some investigation I found out that only versions of Xtext up to 2.7.3 seem to be working correctly with the plugin. From version 2.8.0 onward, all the lines in the feature files show a "No definition found for [...]" warning message.

Thanks in advance for your help!

Cheers,

Pyves
##

**Comment by drkstr101** [comment]
Fixed in current master.

**Comment by PyvesB** [comment]
Good to hear - let's close this issue then!
