### ISSUE TITLE
Cucumber warns about missing inherited steps

### ISSUE THREAD

**Issue by systemovich** [rlogiacco/Natural#49]
I am working in PHP and Behat. Some of the steps are inherited, but the Cucumber editor warns that they are missing. Is there a way to fix this?

**Comment by rlogiacco** [comment]
The plugin scans Java source files for step definitions, meaning the current implementation is capable to support only Java. 
I would personally welcome any contribution adding support for additional languages: are you willing to contribute or do you know anybody willing to do so?

**Comment by systemovich** [comment]
@rlogiacco, I will try to add support for PHP.
