### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Pontesegger** [rlogiacco/Natural#54]
Hi,

I am very interested in pushing this plugin a little and combine it with eclipse.org/ease. Therefore we would require clear licenses as part of the bundles and best also of the source files. From the marketplace I can see that these plugins are available under EPL. However I cannot find refereces to EPL on the github page or within the source files.

**Comment by rlogiacco** [comment]
EPL 1.0 has been added as requested, but I'm not sure I see a practical touch point between EASE and Natural, with the former focusing on scripting languages while the latter focuses on specification languages.

While I would welcome any type of help (the project has been stuck for too long) I would also desire to avoid to see it being used to drive the BDD community toward some sort of _automation scripting language_.

Would you mind to describe what for of combining did you have in mind?

**Comment by Pontesegger** [comment]
Thanks for adding the license. It will be needed when an eclipse projects wants to add a dependency to your code.

EASE provides a testing framework for script languages based on junit. What we intend is to provide a way to execute cucumber *.feature files by providing code generators for script languages and then execute such feature files using our supported script languages.

From Natural we want to use the editor support. Therefore we would need to extend the framework regarding code completion, error markers and quick fix support. Eg in its current state it will not be able to detect glue code written in a script language. Further it would be nice if existing definitions ('Given', 'When', ...) would be used for code completions.

The intention is not that Natural has to depend on EASE. Instead we want to add extension points to Natural where needed, so EASE could contribute its special behavior.

If you are interested in more details, the ease-dev mailing list would be a perfect place to discuss the topic.

cheers
Christian
