### ISSUE TITLE
Syntax highlighting and definition link breaks when there are multiple example tables in a scenario outline

### ISSUE THREAD

**Issue by lnm2** [rlogiacco/Natural#56]
Syntax highlighting breaks and definition links break when there are multiple example tables in a scenario outline for each scenario / outline after the multiple example tables.

Also, there is a syntax error for the first example table when there are multiple example tables:
(mismatched input '@blue' expecting 'Examples:')

![image](https://user-images.githubusercontent.com/37799895/39316747-d285cd9e-4971-11e8-960b-a09d3252b671.png)

**Comment by drkstr101** [comment]
This is most likely related to the lack of support for example tags. I originally thought this was noncompliance to gerhkin spec, but it appears I was mistaken.

**Comment by drkstr101** [comment]
Fixed in https://github.com/rlogiacco/Natural/pull/73
