### ISSUE TITLE
Could not complete install on Eclipse Neon

### ISSUE THREAD

**Issue by larsflyger** [rlogiacco/Natural#57]
Hello, I'm currently trying to install Natural on my Eclipse Neon.3 Release (4.6.3), and I've had several dependency errors trying to complete the installation that I can't figure out:

> Cannot complete the install because one or more required items could not be found.
> Software currently installed: Webclipse Suite 1.11.0.201808131414 (com.genuitec.eclipse.webclipse.suite.feature.group 1.11.0.201808131414)
> Missing requirement: Mars Support 1.11.0.201808131409 (com.genuitec.eclipse.theming.mars.feature.feature.group 1.11.0.201808131409) requires 'org.eclipse.platform.feature.group [4.5.0,4.6.0)' but it could not be found
> Cannot satisfy dependency:
> From: Webclipse Core 1.11.0.201808131414 (com.genuitec.eclipse.webclipse.core.feature.feature.group 1.11.0.201808131414)
> To: com.genuitec.eclipse.concepts com.genuitec.theming.core 0.0.0
> Cannot satisfy dependency:
> From: Webclipse JavaEE Core 1.11.0.201808131414 (com.genuitec.eclipse.webclipse.core.javaee.feature.feature.group 1.11.0.201808131414)
> To: com.genuitec.eclipse.webclipse.core.feature.feature.group 0.0.0
> Cannot satisfy dependency:
> From: Webclipse REST 1.11.0.201808131414 (com.genuitec.eclipse.webclipse.rest.feature.feature.group 1.11.0.201808131414)
> To: com.genuitec.eclipse.webclipse.core.javaee.feature.feature.group 0.0.0
> Cannot satisfy dependency:
> From: Webclipse Suite 1.11.0.201808131414 (com.genuitec.eclipse.webclipse.suite.feature.group 1.11.0.201808131414)
> To: com.genuitec.eclipse.webclipse.rest.feature.feature.group [1.11.0.201808131414]

**Comment by rlogiacco** [comment]
Hi @larsflyger,
You are trying to install on a proprietary version of a web port of Eclipse: sorry I can't help with that.
