### ISSUE TITLE
'no definition found for '<step>' where step expects Integer parameters

### ISSUE THREAD

**Issue by gilesn** [rlogiacco/Natural#59]
For a step expecting integer parameters the editor shows errors 'no definition found for ..'

feature file:
 `Then I expect <number>`

Glue:
`@Then("^I expect (\\d+)$")`

If I change the regexp to `(.*)` the error goes away.

**Comment by drkstr101** [comment]
I was unable to reproduce this error on the latest release. Could you please provide more information on your feature file? A complete test case (feature content) that demonstrates the issue would be ideal.

**Comment by rlogiacco** [comment]
I believe this is a duplicate of #31

**Comment by drkstr101** [comment]
Flagging for review in [next](https://github.com/rlogiacco/Natural/pull/73).
