### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by hurjup** [rlogiacco/Natural#61]
Natural breaks and throws this exception.
```
java.util.regex.PatternSyntaxException: Illegal repetition near index 64
I check response body whether the following message is displayed {string}
```
Code:
```
@Then("I check response body whether the following message is displayed {string}")
public void iCheckResponseBodyWhetherTheFollowingMessageIsDisplayed(String msg) {
...
}
```
Feature:
`Then I check response body whether the following message is displayed "blah blah blah"`

Visually I don't see anything wrong with the code above. Also, colleagues using intellij do not face this problem.

A related concern is that the above problem is triggered in another project sitting in another working set than the one I would like to work on. Is it a design decision, not having per-project database (so empyrically having per-workspace database)?
Also, in general is there a way to force database re-initialization? (Deleting certain files, issuing a super secret keyboard shortcut, etc...)

**Comment by rlogiacco** [comment]
IntelliJ doesn't use Natural, there's no database so no re-initialization is possible, either via secret shortcuts or anything else.

I've been begging for help on this project in each and every possible way, but it seems nobody is willing to stand up and lend me an hand, so the project is where it is and will keep growing dust and issues: I'm not willing to keep donating to a community who hasn't the slightest will to donate back.

It's free and it's there: you can jump into the code and fix the issue if you so like.

Sorry for my ranting, but I'm frustrated.
