### ISSUE TITLE
Unable to install Natural 0.7.6

### ISSUE THREAD

**Issue by sachsgit** [rlogiacco/Natural#62]
I am trying to install Natural 0.7.6 on Eclipse IDE 4.11, and I am getting

> Cannot complete the install because one or more required items could not be found.
>   Software being installed: Cucumber Editor 0.7.6.201505100000 (org.agileware.natural.cucumber.feature.feature.group 0.7.6.201505100000)
>   Missing requirement: Cucumber Editor 0.7.6.201505100000 (org.agileware.natural.cucumber.feature.feature.group 0.7.6.201505100000) requires 'org.eclipse.equinox.p2.iu; org.eclipse.xtext 2.1.0' but it could not be found

Eclipse IDE for Java Developers
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

**Comment by rlogiacco** [comment]
This project has not been updated to the latest versions of Eclipse, so you are left with a few options:

* roll back to a previous version of Eclipse
* help me update the project

I have been asking for help on this project in the past four years without success (most common reason being "I'm not a developer"), so if you want to help me revamp the project you are very welcome, but I know I don't have the time to keep maintaining the project on my own.

**Comment by sachsgit** [comment]
I'm a Software Engineer in Test... so I would love to help... just not sure what's involved.
Can you point me into the direction for what needed to be done to update this project to Eclipse 4.11 (and beyond)?

**Comment by sachsgit** [comment]
Saw the wiki, and trying to install Xtext

**Comment by rlogiacco** [comment]
Keep me posted and I'll try to help you out. Obviously, you need to install
the most recent version of Xtext rather than the one referenced in the
wiki: that one would probably not produce a build compatible with the
latest Eclipse.

**Comment by sachsgit** [comment]
Question: I see there is a warning/error message saying: "gherkin-2.11.2.jar cannot be resolved" which is a "Plug-in Problem". Where does gherkin-2.11.2.jar come from?

I have found "gherkin-6.0.17.jar" from cucumber.io., but that seems to be way off. Or is it?

**Comment by rlogiacco** [comment]
It was the latest version available at that time. Please consider Gherkin
went under heavy refactoring in the latest couple of years so that version
difference is not that much surprising.

We will probably have to do some refactoring as well: I'm quite sure there
are a few things which are not compatible with our source code, even if I
believe there is only one or two calls to the library.

**Comment by sachsgit** [comment]
To "get rid" of the errors I was seeing, I needed to move from Java 1.5 to 1.6. Which did clear out the "errors" but left me with the following "warnings"
Description	Resource	Path	Location	Type
'Automatic-Module-Name' header is required to be discoverable as a Java module in a Java modular setup (Java 9 and later)	MANIFEST.MF	/org.agileware.natural.common/META-INF	line 1	Plug-in Problem
gherkin-6.0.17.jar cannot be resolved	build.properties	/org.agileware.natural.cucumber	line 8	Plug-in Problem
No grammar constraints (DTD or XML Schema) referenced in the document.	plugin.xml	/org.agileware.natural.cucumber	line 1	XML Problem
Referenced resource 'org/agileware/natural/cucumber/Cucumber.genmodel' in attribute 'genModel' cannot be found	plugin.xml	/org.agileware.natural.cucumber	line 6	Plug-in Problem
'Automatic-Module-Name' header is required to be discoverable as a Java module in a Java modular setup (Java 9 and later)	MANIFEST.MF	/org.agileware.natural.cucumber.tests/META-INF	line 1	Plug-in Problem
Unsatisfied version constraint: 'org.objectweb.asm: [5.0.1,6.0.0)'	MANIFEST.MF	/org.agileware.natural.cucumber.tests/META-INF	line 16	Plug-in Problem
The method initializeDefaults() from the type GlobalRegistries is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 20	Java Problem
The method makeCopyOfGlobalState() from the type GlobalRegistries is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 27	Java Problem
The method makeCopyOfGlobalState() from the type GlobalRegistries is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 29	Java Problem
The method restoreGlobalState() from the type GlobalRegistries.GlobalStateMemento is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 57	Java Problem
The method restoreGlobalState() from the type GlobalRegistries.GlobalStateMemento is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 63	Java Problem
The type GlobalRegistries is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 8	Java Problem
The type GlobalRegistries is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 20	Java Problem
The type GlobalRegistries is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 27	Java Problem
The type GlobalRegistries is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 29	Java Problem
The type GlobalRegistries.GlobalStateMemento is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 9	Java Problem
The type GlobalRegistries.GlobalStateMemento is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 15	Java Problem
The type GlobalRegistries.GlobalStateMemento is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 16	Java Problem
The type IInjectorProvider is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 10	Java Problem
The type IInjectorProvider is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 13	Java Problem
The type IInjectorProvider is deprecated	CucumberUiInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 6	Java Problem
The type IInjectorProvider is deprecated	CucumberUiInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 10	Java Problem
The type IRegistryConfigurator is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 11	Java Problem
The type IRegistryConfigurator is deprecated	CucumberInjectorProvider.java	/org.agileware.natural.cucumber.tests/src-gen/org/agileware/natural/cucumber	line 13	Java Problem
'Automatic-Module-Name' header is required to be discoverable as a Java module in a Java modular setup (Java 9 and later)	MANIFEST.MF	/org.agileware.natural.cucumber.ui/META-INF	line 1	Plug-in Problem
This plug-in does not export all of its packages	MANIFEST.MF	/org.agileware.natural.cucumber.ui/META-INF	line 24	Plug-in Problem
Discouraged access: The type 'IPartialContentAssistParser' is not API (restriction on required library 'C:\OpenSource\Eclipse\Eclipse-java-2019-03\plugins\org.eclipse.xtext.ui.codetemplates.ui_2.17.1.v20190402-1603.jar')	PartialCucumberContentAssistParser.java	/org.agileware.natural.cucumber.ui/src-gen/org/agileware/natural/cucumber/ui/contentassist/antlr	line 10	Java Problem
Discouraged access: The type 'IPartialContentAssistParser' is not API (restriction on required library 'C:\OpenSource\Eclipse\Eclipse-java-2019-03\plugins\org.eclipse.xtext.ui.codetemplates.ui_2.17.1.v20190402-1603.jar')	PartialCucumberContentAssistParser.java	/org.agileware.natural.cucumber.ui/src-gen/org/agileware/natural/cucumber/ui/contentassist/antlr	line 18	Java Problem
The type ISemanticHighlightingCalculator is deprecated	CucumberUiModule.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui	line 15	Java Problem
The type ISemanticHighlightingCalculator is deprecated	CucumberUiModule.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui	line 42	Java Problem
The import org.eclipse.xtext.Assignment is never used	CucumberProposalProvider.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/contentassist	line 11	Java Problem
The method addPosition(int, int, String...) from the type IHighlightedPositionAcceptor is deprecated	SemanticHighlightingCalculator.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/syntaxcoloring	line 39	Java Problem
The method addPosition(int, int, String...) from the type IHighlightedPositionAcceptor is deprecated	SemanticHighlightingCalculator.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/syntaxcoloring	line 53	Java Problem
The type IHighlightedPositionAcceptor is deprecated	SemanticHighlightingCalculator.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/syntaxcoloring	line 11	Java Problem
The type IHighlightedPositionAcceptor is deprecated	SemanticHighlightingCalculator.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/syntaxcoloring	line 16	Java Problem
The type IHighlightedPositionAcceptor is deprecated	SemanticHighlightingCalculator.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/syntaxcoloring	line 36	Java Problem
The type IHighlightedPositionAcceptor is deprecated	SemanticHighlightingCalculator.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/syntaxcoloring	line 49	Java Problem
The type ISemanticHighlightingCalculator is deprecated	SemanticHighlightingCalculator.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/syntaxcoloring	line 12	Java Problem
The type ISemanticHighlightingCalculator is deprecated	SemanticHighlightingCalculator.java	/org.agileware.natural.cucumber.ui/src/org/agileware/natural/cucumber/ui/syntaxcoloring	line 14	Java Problem
'Automatic-Module-Name' header is required to be discoverable as a Java module in a Java modular setup (Java 9 and later)	MANIFEST.MF	/org.agileware.natural.cucumber/META-INF	line 1	Plug-in Problem
Unsatisfied version constraint: 'org.objectweb.asm: [5.0.1,6.0.0)'	MANIFEST.MF	/org.agileware.natural.cucumber/META-INF	line 24	Plug-in Problem
A keyword should not contain spaces.	Cucumber.xtext	/org.agileware.natural.cucumber/src/org/agileware/natural/cucumber	line: 29 /org.agileware.natural.cucumber/src/org/agileware/natural/cucumber/Cucumber.xtext	Grammar Problem
Referenced resource 'org/agileware/natural/jbehave/JBehave.genmodel' in attribute 'genModel' cannot be found	plugin.xml	/org.agileware.natural.jbehave	line 7	Plug-in Problem
'Automatic-Module-Name' header is required to be discoverable as a Java module in a Java modular setup (Java 9 and later)	MANIFEST.MF	/org.agileware.natural.jbehave.tests/META-INF	line 1	Plug-in Problem
Unsatisfied version constraint: 'org.objectweb.asm: [5.0.1,6.0.0)'	MANIFEST.MF	/org.agileware.natural.jbehave.tests/META-INF	line 16	Plug-in Problem
The method initializeDefaults() from the type GlobalRegistries is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 20	Java Problem
The method makeCopyOfGlobalState() from the type GlobalRegistries is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 27	Java Problem
The method makeCopyOfGlobalState() from the type GlobalRegistries is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 29	Java Problem
The method restoreGlobalState() from the type GlobalRegistries.GlobalStateMemento is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 57	Java Problem
The method restoreGlobalState() from the type GlobalRegistries.GlobalStateMemento is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 63	Java Problem
The type GlobalRegistries is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 8	Java Problem
The type GlobalRegistries is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 20	Java Problem
The type GlobalRegistries is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 27	Java Problem
The type GlobalRegistries is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 29	Java Problem
The type GlobalRegistries.GlobalStateMemento is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 9	Java Problem
The type GlobalRegistries.GlobalStateMemento is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 15	Java Problem
The type GlobalRegistries.GlobalStateMemento is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 16	Java Problem
The type IInjectorProvider is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 10	Java Problem
The type IInjectorProvider is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 13	Java Problem
The type IInjectorProvider is deprecated	JBehaveUiInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 6	Java Problem
The type IInjectorProvider is deprecated	JBehaveUiInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 10	Java Problem
The type IRegistryConfigurator is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 11	Java Problem
The type IRegistryConfigurator is deprecated	JBehaveInjectorProvider.java	/org.agileware.natural.jbehave.tests/src-gen/org/agileware/natural/jbehave	line 13	Java Problem
'Automatic-Module-Name' header is required to be discoverable as a Java module in a Java modular setup (Java 9 and later)	MANIFEST.MF	/org.agileware.natural.jbehave.ui/META-INF	line 1	Plug-in Problem
This plug-in does not export all of its packages	MANIFEST.MF	/org.agileware.natural.jbehave.ui/META-INF	line 22	Plug-in Problem
Discouraged access: The type 'IPartialContentAssistParser' is not API (restriction on required library 'C:\OpenSource\Eclipse\Eclipse-java-2019-03\plugins\org.eclipse.xtext.ui.codetemplates.ui_2.17.1.v20190402-1603.jar')	PartialJBehaveContentAssistParser.java	/org.agileware.natural.jbehave.ui/src-gen/org/agileware/natural/jbehave/ui/contentassist/antlr	line 10	Java Problem
Discouraged access: The type 'IPartialContentAssistParser' is not API (restriction on required library 'C:\OpenSource\Eclipse\Eclipse-java-2019-03\plugins\org.eclipse.xtext.ui.codetemplates.ui_2.17.1.v20190402-1603.jar')	PartialJBehaveContentAssistParser.java	/org.agileware.natural.jbehave.ui/src-gen/org/agileware/natural/jbehave/ui/contentassist/antlr	line 18	Java Problem
'Automatic-Module-Name' header is required to be discoverable as a Java module in a Java modular setup (Java 9 and later)	MANIFEST.MF	/org.agileware.natural.jbehave/META-INF	line 1	Plug-in Problem
Unsatisfied version constraint: 'org.objectweb.asm: [5.0.1,6.0.0)'	MANIFEST.MF	/org.agileware.natural.jbehave/META-INF	line 22	Plug-in Problem

I have forked your project to my own, and working there. 

It does seem to run on my machine, but this is the first eclipse plugin I have worked on.
I can see "Cucumber" and "JBehave" in the Windows -> Preferences menu list, when I run the plugin, although with the other plugins that I am using (TestNG, Maven, etc.).

Is there a better way of communicating than this? Or is this okay with you?

**Comment by rlogiacco** [comment]
The messages you copy pasted are practically unreadable, but I believe the warnings are mostly related to the upgrades in the eclipse plugin management.

If you prefer Ican open up a channel on slack where communication might be easier.

**Comment by rlogiacco** [comment]
After applying some formatting I also see warnings due to deprecated operations in the Xtext libraries: I guess there’s some additional work required to get rid of those.
Anyway, if you focus on having it running I can focus on the necessary refactoring to have it updated to the latest version.

**Comment by rlogiacco** [comment]
Here the invitation to the brand new [slack team](https://join.slack.com/t/natural-world/shared_invite/enQtNjI4OTI1MjY2MzA1LTUwOWJlNmNlNmEyYjQxNTBiNWYyMTZhNTAwZjEwOTNmNjk5YmFiOTE3Mjk0ZGY1ODFiMmRhYjc0NzMzYWQ2ZTI)

**Comment by sachsgit** [comment]
Signed into the slack team. Haven't used slack much.

HAd to reinstall Eclipse, and I was able to install from Eclipse Marketplace. Still, want to help and clean up the code.

**Comment by sachsgit** [comment]
Slack is blocked at work.

**Comment by Rocky007QA** [comment]
I'm also facing an issue to install Natural 0.7.6 plugin in Eclips Mars. Below is the screen shot of error. This is first time installing the plugin. Could you please help to resolve this issue.

![image](https://user-images.githubusercontent.com/53486836/62144728-f18de380-b30f-11e9-9e95-21689c8b1482.png)

**Comment by devendra-qa** [comment]
I am also facing issue while installing Natural plug-in and getting below error

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Multiple problems occurred while downloading.
HTTP Server 'Service Unavailable': http://download.eclipse.org/m2e-wtp/signed/mavenarchiver/0.17.1/plugins/org.sonatype.m2e.mavenarchiver_0.17.1.201605251832-signed-20160525150658.jar.pack.gz
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/m2e-wtp/signed/mavenarchiver/0.17.1/plugins/org.sonatype.m2e.mavenarchiver_0.17.1.201605251832-signed-20160525150658.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/m2e-wtp/signed/mavenarchiver/0.17.1/features/org.sonatype.m2e.mavenarchiver.feature_0.17.1.201605251832-signed-20160525150658.jar
HttpComponents connection error response code 503.

**Comment by devendra-qa** [comment]
please help in resolving above issue. Also it taking complete day to install and then get this error

**Comment by rlogiacco** [comment]
@devendra-qa sure, here are the instructions: 
1. fork this repository
2. clone the forked repository on your computer
3. use the latest Xend IDE to rebuild the plugin with the latest dependencies.

Once you have it working, feel free to share your changes via a pull request.

**Comment by rlogiacco** [comment]
> Also it taking complete day to install and then get this error

You are aware you got the entire software for free, right? Because I had the impression from you consider your "complete day" somehow more valuable than the many nights I've spent to code this plugin....

**Comment by devendra-qa** [comment]
@rlogiacco Thanks a lot

**Comment by miklossy** [comment]
I could successfully install Natural (Cucumber Editor 0.7.6, JBehave Editor 0.3.0) into Eclipse 2020-03 (4.15.0).

@devendra-qa : Does the installation problem still exist on your computer?

**Comment by hiranyaa** [comment]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Cucumber Editor 0.7.6.201505100000 (org.agileware.natural.cucumber.feature.feature.group 0.7.6.201505100000)
  Missing requirement: Cucumber Editor 0.7.6.201505100000 (org.agileware.natural.cucumber.feature.feature.group 0.7.6.201505100000) requires 'org.eclipse.xtext 2.1.0' but it could not be found

**Comment by miklossy** [comment]
If I install Natural (Cucumber Editor 0.7.6, JBehave Editor 0.3.0) into Eclipse 2020-03 (4.15.0), it automatically picks up `Xtext 2.21`. I wonder where the `org.eclipse.xtext 2.1.0` dependency comes from.
@hiranyaa In which Eclipse enviroment do you try to install Natural?

**Comment by drkstr101** [comment]
@devendra-qa your issue appears to be a random failure reading Eclipse repos, which can be somewhat frequent during periods of heavy traffic.

As for the Natural dependency errors, I have verified the latest release works in both Eclipse Mars, and Eclipse 2020-03. More info is needed about your specific setup if you are getting install errors not related to random repo failures due to traffic.

**Comment by rlogiacco** [comment]
> I'm also facing an issue to install Natural 0.7.6 plugin in Eclips Mars. Below is the screen shot of error. This is first time installing the plugin. Could you please help to resolve this issue.

I don't see any issue: it is asking for confirmation as Natural is not an officially signed plugin, but a community contributed one...

**Comment by rlogiacco** [comment]
Please let us know if you still have this issue with version `0.7.7` because that should have been fixed now.

**Comment by DineshGunna** [comment]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Cucumber Editor 0.7.7.202005221158 (org.agileware.natural.cucumber.feature.feature.group 0.7.7.202005221158)
  Missing requirement: Cucumber Editor 0.7.7.202005221158 (org.agileware.natural.cucumber.feature.feature.group 0.7.7.202005221158) requires 'org.eclipse.equinox.p2.iu; com.google.inject 3.0.0' but it could not be found

**Comment by sachsgit** [comment]
@DineshGunna , when that happened to me, it involved a firewall restriction.
Are you behind a firewall?

**Comment by KarGop** [comment]
am trying to install in linux machine. It shows path not found "http://rlogiacco.github.com/Natural"

**Comment by sachsgit** [comment]
@KarGop For some reason, I, too, have a problem with that link as well.
[https://github.com/rlogiacco/Natural](https://github.com/rlogiacco/Natural) does work for me, so try using that one.

**Comment by KarGop** [comment]
@sachsgit Thank you for your reference. I tried that one(http://github.com/rlogiacco/Natural). Again I am facing the same error "could not find http://github.com/rlogiacco/Natural"

**Comment by sachsgit** [comment]
@KarGop That is strange, I have to wonder about firewall or permissions then.
What are you using to connect? If it's Eclipse, does it have its own Keystore? Is github.com within the Keystore? Same for Java.
This [article](https://stackoverflow.com/questions/684081/importing-ssl-certificate-into-eclipse) might help you

**Comment by mijain-conga** [comment]
To add Natural Plugin in eclipse, try using URL - http://rlogiacco.github.io/Natural.

**Comment by mitujain01** [comment]
To add Natural Plugin in eclipse, try using URL - http://rlogiacco.github.io/Natural.

**Comment by sachsgit** [comment]
By using the "Help > Install New Software...." and using that URL to manually install Natural, I was successful.
Thanks @mitujain01
