### ISSUE TITLE
buildproperties: jars.extra.classpath has been deprecated

### ISSUE THREAD

**Issue by sachsgit** [rlogiacco/Natural#63]
I was looking at [Feature and Plug-in Build Configuration Properties](https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Freference%2Fpde_feature_generating_build.htm) webpage and I noticed that:

> **Plug-in specific properties**
> **extra.<library>** - extra classpaths used to perform automated build. Classpath can either be relative paths, or platform urls referring to plug-ins and fragments of your development environment (e.g. ../someplugin/xyz.jar, platform:/plugins/org.apache.ant/ant.jar). Platform urls are recommended over relative paths;
> **jars.extra.classpath** - (**deprecated**) same effect than extra.<library> except that the entries are applied to all libraries;

PS: @rlogiacco Still around, just having some computer problems and work-issues, but still wanting and willing to help you clear out the warnings and update the code as I can.

**Comment by drkstr101** [comment]
Thanks for the tip! These references have been removed in the latest PR.

**Comment by rlogiacco** [comment]
@sachsgit this would be a great time to jump in: @drkstr101 is hardly working on a huge rewrite ;)

**Comment by drkstr101** [comment]
@rlogiacco I believe this issue can be closed.
