### ISSUE TITLE
allow tag for scenatrio outline 

### ISSUE THREAD

**Issue by Bokatbo** [rlogiacco/Natural#64]
Use of tags in  scenario-outline should be allowed, it is not today. See example below

  @123
  Scenario Outline: using Scheduled Task.
    Given  a banana on the market "settlePlace"
    When the banana is sold
    Then the status should be "status"

 @fr
    Examples: 
      | settlePlace       | status |
      | France              | VERIFIED    |
 
 @CH @BCDEF
    Examples: 
      | settlePlace      | status |
      | China              | VERIFIED    |
      | Boubou           | VERIFIED    |

**Comment by drkstr101** [comment]
I couldn't find any reference to this being valid Gherkin syntax.

https://cucumber.io/docs/gherkin/reference/
https://github.com/featurist/node-ebnf-diagram/blob/master/test/gherkin.ebnf (unofficial)
https://github.com/cucumber-attic/gherkin2/wiki/BNF (unofficial)

If you could point to the appropriate spec which claims this is valid Gherkin syntax we will make sure it is supported in the next grammar update

**Comment by drkstr101** [comment]
Fixed in https://github.com/rlogiacco/Natural/pull/73

**Comment by drkstr101** [comment]
PS: There was another open Issue which was also using tags on examples. Two people using the same pattern was proof enough in my book!

**Comment by Bokatbo** [comment]
Thanks..there is none officiel reference for this tags pattern, but we find
it powerfull to choose different tags to execute different example.
Thanks. Good job.
   Boris.

tor. 7. maj 2020 23.45 skrev Aaron R. Miller <notifications@github.com>:
