### ISSUE TITLE
Error Reading Update site

### ISSUE THREAD

**Issue by sachsgit** [rlogiacco/Natural#65]
Hi,

I am seeing:

> Error reading update site http://rlogiacco.github.com/Natural.
> White spaces are required between publicId and systemId.

StackOverview has: https://stackoverflow.com/questions/6514158/white-spaces-are-required-between-publicid-and-systemid

> The error message is actually correct if not obvious. It says that your DOCTYPE must have a SYSTEM identifier. I assume yours only has a public identifier.
> 
> You'll get the error with (for instance):
> 
> <!DOCTYPE persistence PUBLIC
>     "http://java.sun.com/xml/ns/persistence/persistence_1_0.xsd">
> You won't with:
> 
> <!DOCTYPE persistence PUBLIC
>     "http://java.sun.com/xml/ns/persistence/persistence_1_0.xsd" "">
> Notice "" at the end in the second one -- that's the system identifier. The error message is confusing: it should say that you need a system identifier, not that you need a space between the publicId and the (non-existent) systemId.
> 
> By the way, an empty system identifier might not be ideal, but it might be enough to get you moving.

The only `DOCTYPE` I can find is `Natural\org.agileware.natural.cucumber\plugin.xml`
You can try to have a different docType, but I just deleted the line, and it seems to be working.

**Comment by miklossy** [comment]
I could successfully install Natural (Cucumber Editor 0.7.6, JBehave Editor 0.3.0) into Eclipse 2020-03 (4.15.0).

@sachsgit Does the installation problem still exist on your computer?

**Comment by sachsgit** [comment]
@miklossy Yes, it does. Although, some of it, is a firewall issue with github.io.

**Comment by rlogiacco** [comment]
Honestly, I can't reproduce it. Please let us know if this still happens after the release of `0.7.7` and `0.3.1` and I'll reopen the issue.
