### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [rlogiacco/Natural#66]
Hello Natural team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Natural project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by drkstr101** [comment]
@rlogiacco This is now complete. Issue can be closed.

**Comment by rlogiacco** [comment]
I’m closing the issue @drkstr101 , but I kindly ask you to have yourself added to the list of authors of the plugin, please.

Thank you!

**Comment by miklossy** [comment]
I also think that @drkstr101 deserved to be listed as the authors of the project. I created a [PR](https://github.com/eclipse/xtext/pull/1795/files) where he is also listed.

**Comment by rlogiacco** [comment]
Thank you

**Comment by miklossy** [comment]
The `Natural` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html). Thank you @rlogiacco and @drkstr101 !
