### ISSUE TITLE
How may I be of service

### ISSUE THREAD

**Issue by drkstr101** [rlogiacco/Natural#68]
Hello again!

I'm starting to get the hang of things over here, and wanted to see if there was anything specific you wanted me to focus on. Preferably something small(ish) that I can wrap my head around. =)

In the meantime, I've started a branch in my fork where I've upgraded to the latest tooling and set the Java version to 1.8. I'm hoping this will make it easier to fully support Groovy and Kotlin, but let me know if there are any hard requirements to support older versions.

My next plan is to just tinker around a bit and see if I can create a few test cases that explore my understanding of the functionality. But again, please let me know if there are any areas you think I should focus on first.

Cheers, and thanks for your time!

**Comment by rlogiacco** [comment]
Hi Aaron, we might want to find a different way to communicate other than via Issues... I'll send you my Telegram ID so we can have more lively conversations if needed.

Anyway, there are a couple of high priority things I have in my list, but they aren't "food for an appetizer", so I double your plan: just let me know if there's anything I can help with.

Go ahead with the jdk upgrade: 1.8 seems more than a reasonable entrypoint.
