### ISSUE TITLE
Step identification rules in Natural not the same as in Cucumber

### ISSUE THREAD

**Issue by TrueDub** [rlogiacco/Natural#7]
I had a step as follows:

`And a label saying "Address:" is  not displayed.`

note the double space between is and not.

My step definition had

`And a label saying "Address:" is not displayed.`

no double space.

Natural connected the two and said the step was defined, but when I ran the test case cucumber gave a PendingException saying that the step did not exist.

Possibly Natural's rules are slightly looser than Cucumber's?
##

**Comment by drkstr101** [comment]
Flagging for review in [next](https://github.com/rlogiacco/Natural/pull/73)

**Comment by drkstr101** [comment]
@rlogiacco Jbehave has been totally reworked in next. This can probably be closed out as no longer relevant. Otherwise feature-request it for fine-tuned Jbehave formatter rules. (it should be fairly close to Cucumber formatter as is). Cucumber formatter would probably get priority though, yes?

**Comment by rlogiacco** [comment]
Yup 👍
