### ISSUE TITLE
Not able to navigate to step definition from the feature file

### ISSUE THREAD

**Issue by ApurvaNayak** [rlogiacco/Natural#74]
**Description:** I am unable to navigate to step definition when I command+click on the steps from feature file. However, the scripts are working fine when we run through jUnit or Maven and there are no issues finding the step definition.

- **Eclipse version:**                  2020-03 (4.15.0)
- **Build ID:**                               20200313-1211
- **Plugins:**
- Natural 0.7.6 (installed from market place with cucumber editor)
- Cucumber Eclipse 1.0.0.202001082311
- **OS:**                                         MacOS

**Snapshot of the plugins installed:**
![image](https://user-images.githubusercontent.com/64984377/81335503-b88c5780-9075-11ea-8794-efd6df96230f.png)

 
**Snapshot of the Runner file and project folder structure:**
![image](https://user-images.githubusercontent.com/64984377/81335524-be823880-9075-11ea-9a0d-81190089257c.png)

 
**Snapshot of the feature file:**
![image](https://user-images.githubusercontent.com/64984377/81335540-c510b000-9075-11ea-857b-7aa1d8cb4af6.png)
 

 
Below are the steps I have tried and have not got any success:

- Uninstall the plug ins
- Restart the eclipse
- Reinstall the plugins from the market place
- Restart the eclipse
- Convert the project to Cucumber project.

 
Could someone please check and let me know where am I going wrong and if someone can please help me out with the solution. Also, please note that everything was working fine just until 2 days ago and all of the sudden it has stopped working.
 
Changes done within these two days were nothing but moving the feature files from one folder to other folder. Earlier I had all the files in just one folder and it was tedious to maintain it so created multiple folder based on my project structure and moved the files in the respective folders.

Would appreciate all the help and pointers i can get from the experts here.

**Comment by drkstr101** [comment]
Hi ApurvaNayak,

Sorry to hear you are running into trouble. The current release on the Marketplace is actually 5 years old at this point. There will actually be an update soon (within days) that may address this problem, but there are no specific changes that change this behavior, so it could be entirely unrelated to Natural.

I will do some testing on the upcoming release and make sure linking to step definitions is working as expected.

All the best,
~Aaron

**Comment by ApurvaNayak** [comment]
Thanks much Aaron. I will wait for the update and see if that helps me resolving the issue. It is really giving me hard time without the linkage.

**Comment by drkstr101** [comment]
Also, it looks like this problem may have been around for a while.

https://github.com/rlogiacco/Natural/issues/51
 
There must be something strange in the workspace setup that's causing it to fail. More testing definitely needs to be done to ensure this is working correctly in the upcoming release.

**Comment by ApurvaNayak** [comment]
@drkstr101,

Hello Aaron,

Just wanted to check if we had the updates out? if Not, do we have any tentative plans ?

**Comment by rlogiacco** [comment]
Have you tried the latest release, `0.7.7`?

**Comment by ApurvaNayak** [comment]
> Have you tried the latest release, `0.7.7`?

Yes Aaron. Today i updated the release to 0.7.7 and the problem is still persistent. I am still facing the issue which was reported.

**Comment by rlogiacco** [comment]
Thanks. 
The issue you are reporting is related to the use of the placeholder within the `ScenarioOutline` which has never worked properly: our step matching algorithm is unable to resolve the placeholder,  thus unable to find a matching step.

I guess you are left with a few options: 

1. step in and solve the problem yourself, maybe contributing your solution back to the project
2. wait until we decide to prioritize this issue
3. use the *Sponsor* button at the top of the page to discover how to force your priorities on us :smile:

I'll leave this issue open as a reminder of the problem.

**Comment by rlogiacco** [comment]
Duplicate of #40
