### ISSUE TITLE
Add Language Server Protocol Support to the Gherkin Language

### ISSUE THREAD

**Issue by miklossy** [rlogiacco/Natural#79]
Since [Xtext 2.13](https://blogs.itemis.com/en/eclipse-xtext-2.13-is-released) there is a support for building Language Server packages for Xtext-based languages.

It would be nice to add this LSP Support to the Gherkin Language to be able to use it in different editors, such as Atom, Theia, Visual Studio Code, ...

See also the [List of Language Servers](https://microsoft.github.io/language-server-protocol/implementors/servers/) and the [List of tools supporting the LSP](https://microsoft.github.io/language-server-protocol/implementors/tools/).

**Comment by rlogiacco** [comment]
Jump in mate and help us out :-D

**Comment by drkstr101** [comment]
Support for VSCode/Web based editors is coming up in the next release, which should be wrapped up today or tomorrow. However, they probably won't be fully supported until beta (Natural 2.0) is stable, which is coming a bit later.

**Comment by drkstr101** [comment]
Added LSP support in https://github.com/rlogiacco/Natural/pull/82

Cheers!

**Comment by drkstr101** [comment]
@rlogiacco This has already landed in master, so can probably be closed out.
