### ISSUE TITLE
github-actions event timing

### ISSUE THREAD

**Issue by drkstr101** [rlogiacco/Natural#85]
Is the short timer on the "Stale" tag intentional? I frequently get full pages of notifications from `github-actions` which I have not been able to figure out how to filter. I was wondering if maybe this was a misconfiguration somewhere, or if you wanted to ensure old tickets are frequently touched.

**Comment by rlogiacco** [comment]
I changed it so that now applies only to those labeled as “Pending
Feedback”...
It wasn’t intentional and I found it annoying as well 👍

**Comment by drkstr101** [comment]
Cheers mate!
